name: Build Arch kernel TKG-PDS (Custom)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0" # build mingguan

env:
  _cpusched: "pds"
  _processor_opt: "native"
  _compiler: "llvm"
  _lto_mode: "full"
  _kernel_localversion: "-tkg-pds"
  PKGDEST: "/tmp/linux-tkg"

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install git
        run: pacman -Syu --noconfirm git base-devel sudo

      - name: Checkout linux-tkg
        uses: actions/checkout@v4

      - name: Prepare makepkg user
        run: |
          useradd -m user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R user .

      - name: Compile Kernel
        run: su --preserve-environment user -c "yes '' | makepkg --noconfirm -s"

      - name: Rename kernel config
        run: mv kernelconfig.new kernelconfig.arch.${{ env._cpusched }}.txt || true

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: "linux-tkg-${{ env._cpusched }}-${{ github.run_number }}"
          name: "Linux TKG ${{ env._cpusched }} Build #${{ github.run_number }}"
          files: |
            ${{ env.PKGDEST }}/linux*.pkg.tar.zst
            kernelconfig*.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
